Vocab size : 53
---------------------Starting training---------------------

















  1%|█▉                                                                                                                                                                           | 97/8647 [00:35<47:58,  2.97it/s]
  0%|                                                                                                                                                                                       | 0/100 [00:00<?, ?it/s]
  1%|██                                                                                                                                                                          | 101/8647 [00:42<59:20,  2.40it/s]
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    step(model, optimizer, scheduler, train_loader, test_dataset, device, epoch, path, best_loss = 1000)
  File "train.py", line 66, in step
    test_loss, best_loss = test_for_n_steps(model, test_dataset, device, path, best_loss, epoch, n_steps = 100, step = idx)
  File "train.py", line 115, in test_for_n_steps
    for idx,(context, targets) in enumerate(subset_dataloader):
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 364, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 364, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/dataset.py", line 38, in __getitem__
    inputs = self.df_dataset.iloc[idx]['input']
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/hugo/Desktop/Projects/conditionned_theatre_play_generation/.env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1653, in _getitem_axis
    raise TypeError("Cannot index by location index with a non-integer key")
TypeError: Cannot index by location index with a non-integer key